site_name: Contrast-agent based perfusion MRI lexicon (CAPLEX) v1.0.1
site_description: CAPLEX
site_author: Open Science Initiative for Perfusion Imaging (OSIPI)

theme:
  name: material
  logo: OSIPI_logo.png

docs_dir: docs

nav:
  - Introduction: index.md
  - Section Q- Quantities: quantities.md
  - Section P-Perfusion processes: perfusionProcesses.md
  - Section M-Perfusion models: perfusionModels.md
  - Section G-General purpose processes: generalPurposeProcesses.md

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      features:
        - search.suggest
      
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
